### ISSUE TITLE
getAllKeys method

### ISSUE THREAD

**Issue by ArnoldZokas** [opentable/hobknob-client-nodejs#12]
I want to be able to fetch all keys for my application.

Any objections to me sending a PR for a new client method?

```javascript
function getKeys() {
    // returns array of keys
}
```

**Comment by christriddle** [comment]
Call it getAll and we have a deal

**Comment by christriddle** [comment]
Or if you can wait a few days, this would be a good task for James W and I to work on in our first mentoring session.

**Comment by ArnoldZokas** [comment]
Ok, sounds good.
It is not urgent, so I can wait.

**Comment by ArnoldZokas** [comment]
what is the status of this?

**Comment by jwhyte88** [comment]
Hey @ArnoldZokas - this has been done. cheers!
